name: build code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: "checkout code"
        uses: actions/checkout@v4

      - name: "add thumbv7em-none-eabihf target to toolchain"
        run: rustup target add thumbv7em-none-eabihf
      
      - name: build
        run: cargo build --verbose --release

      - name: "upload binary artifact"
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: target/thumbv7em-none-eabihf/release/build_led-rs


    
